# Site Settings
title: Geekit | Uncle Bob
email: peter2008.ok@163.com
description: We are all in the gutter , but some of us are looking at the stars.
baseurl: /geekit # the subpath of your site, e.g. /blog
url: "https://unclebob7.github.io/geekit/" # https://www.rossener.com
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Geekit
user_description: Uncle Bob


# Social Media
# Remove the item if you don't need it
github_username: unclebob7
facebook_username: facebook_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: "https://github.com/unclebob7/geekit/about/"

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
